# Generated by Django 3.2.5 on 2021-08-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.IntegerField(),
        ),
    ]
