# Generated by Django 3.2.5 on 2021-08-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210822_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='car_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='car_model',
            new_name='model',
        ),
        migrations.AlterField(
            model_name='cars',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
