# Generated by Django 3.2.5 on 2021-09-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210822_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name_plural': 'cars_list'},
        ),
    ]
